#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.

if [ "$#" -lt 4 ]; then
	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	        exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/ 

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
	    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
    else
	        echo "Error: File transfer failed."
fi
